spring:
  profiles: peer1
  application:
    name: stream-kafka-producer
  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        output:
          destination: event-demo
          content-type: text/plain
          producer:
            partitionCount: 1
server:
  port: 7201

---

