spring:
  application:
    name: dalston-config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chiminwon/Config-repo
          basedir: C:\Tools\workspace\Git\Config-repo
#          uri: http://git.oschina.net/didispace/config-repo-demo/
#          uri: https://github.com/chiminwon/config-repo-demo.git
#          username: chiminwon@gmail.com
#          password: 1qaz!QAZ
#          skipSslValidation: true
#          timeout: 5
#          search-paths: repo
#          default-label: master
    bus:
      trace:
        enabled: true
  # 配置rabbitmq的地址以及用户密码
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
  endpoint:
    bus-refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh
server:
  port: 1501
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka

