spring:
  application:
    name: dalston-eureka-server-ha
  profiles: peer1
server:
  port: 1001
#  jetty:
#    acceptors: 2
#    selectors: 4
eureka:
  environment: Dev
  instance:
    prefer-ip-address: true
    hostname: localhost
#    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  server:
    enable-self-preservation: false
  client:
    #Register himself to the center
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1001/eureka,http://127.0.0.1:1002/eureka

---

spring:
  application:
    name: dalston-eureka-server-ha
  profiles: peer2
server:
  port: 1002
eureka:
  environment: Dev
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
  server:
    enable-self-preservation: false
  client:
    #Register himself to the center
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:1002/eureka,http://localhost:1001/eureka