spring:
  profiles: peer1
  application:
    name: dalston-eureka-consumer-ribbon-hystrix
  zipkin:
    base-url: http://localhost:1601
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 1021
eureka:
  client:
    #Enable health check
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
swagger:
  base-package: com.ming
##设置策略
#dalston-eureka-consumer-ribbon-hystrix:
#  ribbon:
#    #随机算法
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #轮训算法
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

---

spring:
  profiles: peer2
  application:
    name: dalston-eureka-consumer-ribbon-hystrix
  zipkin:
    base-url: http://localhost:1061
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 1022
eureka:
  client:
    #Enable health check
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
swagger:
  base-package: com.ming
